export enum CustomerType {
  TAKEAWAY_CUSTOMER = 'TAKEAWAY_CUSTOMER',
  ONLINE_CUSTOMER = 'ONLINE_CUSTOMER',
  THIRD_PARTY_CUSTOMER = 'THIRD_PARTY_CUSTOMER',
  WALK_IN_CUSTOMER = 'WALK_IN_CUSTOMER'
}
